package org.stockinsight.signal;

/** 신호 유형 코드 (D-35, ai-analysis.md §3.7). */
public enum SignalType {
    FIN_REVENUE_CHANGE,
    FIN_OPERATING_MARGIN_CHANGE,
    FIN_OPERATING_TURN,
    FIN_DEBT_RATIO_JUMP,
    FIN_OPERATING_LOSS_STREAK,
    FIN_CAPITAL_IMPAIRMENT,

    FIN_DATA_HISTORY_SHORT,
    FIN_DATA_FINANCIAL_FORMAT,
    FIN_DATA_REVENUE_MISSING,
    FIN_DATA_BASIS_CHANGED,
    FIN_DATA_IRREGULAR_PERIOD,
    FIN_DATA_INCONSISTENT,
    FIN_DATA_STALE
}
